# Generated by Django 4.0.2 on 2022-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_password_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
